nome = str(input(' Digite aqui seu nome completo: '))
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é ',nome.upper())
print('Seu nome em letras minúsculas é',nome.lower())
primeiro = nome.split()
qtd = len(primeiro[0])
total = len(''.join(primeiro))
print('Seu primeiro nome tem {} letras'.format(qtd))
print('Seu nome tem ao todo {} letras'.format(total))

# 2° FORMA PARA RESOLVER
nome = str(input(' Digite aqui seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é {}'.format(nome.upper()))
print('Seu nome em letras minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
# print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))